config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
        registrations: 'customers/registrations'
      }
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "customer_pages#dashboard"
  get "admins/dashboard" => "admin_pages#dashboard", as: :admin_dashboard
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :full_name , presence: :true
end

app/models/food.rb
class Food < ApplicationRecord
end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController
    before_action :authenticate_admin!
    def dashboard
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private
    
    def after_sign_in_path_for(signed_in_user)
        if signed_in_user.is_a?(Admin)
          admin_dashboard_path
        else
          root_path
        end
     end


end

app/controllers/customer_pages_controller.rb
class CustomerPagesController < ApplicationController
    def dashboard
        @foods = Food.all
    end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/foods_controler.rb
class FoodsController < ApplicationController
end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/views/admin_pages/dashboard.html.erb
Admin Dashboard

app/views/customer_pages/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= food.description %>
  </p>
  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>
</div>

app/views/customer_pages/dashboard.html.erb
<h1>Menu</h1>
<div id="foods">
  <% @foods.each do |f| %>
    <%= render partial: 'customer_pages/food' , locals: { food: f } %>
  <% end %>
</div>

app/views/customer_pages/index.html.erb
<h1>Menu</h1>
<div id="foods">
  <% @foods.each do |f| %>
    <%= render partial: 'customer_pages/food' , locals: { food: f } %>
  <% end %>
</div>
<%= button_to "Sign Out", destroy_customer_session_path, method: :delete%>

app/views/customers/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/customers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/foods/index.html.erb
<h1>Menu</h1>
<div id="foods">
  <% @foods.each do |food| %>
    <%= render food %>
  <% end %>
</div>
<%= button_to "Sign Out", destroy_customer_session_path, method: :delete%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodCart2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header>
      <% if admin_signed_in? %>
        <%= render 'shared/admin_navbar'%>
      <% else %>
        <%= render 'shared/customer_navbar'%>
      <% end %>
    </header>
    <main class = "container-fluid main-content">
      <%= render 'shared/flash'%>
      <%= yield %>
    </main>
    <footer>
    </footer>
  </body>
</html>

app/views/shared/_admin_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Admin Food Cart" , admin_dashboard_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Food Cart</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3 me-auto ms-auto">
          <li class="nav-item">
            <%= button_to "Add New Food Item" , destroy_admin_session_path, method: :delete, class: "nav-link active"%>
          </li>
          <li class="nav-item">
            <%= button_to "Restock Food Item" , destroy_admin_session_path, method: :delete, class: "nav-link active"%>
          </li>
          <li class="nav-item">
            <%= button_to "View Orders" , destroy_admin_session_path, method: :delete, class: "nav-link active"%>
          </li>
        </ul>
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <% if admin_signed_in? %>
            <li class="nav-item">
              <%= button_to "Log out" , destroy_admin_session_path, method: :delete, class: "nav-link active"%>
            </li>
            <li class="nav-item">
              <%= link_to "Profile", edit_admin_registration_path, class: "nav-link active"%>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign in" , new_admin_session_path, class: "nav-link active"%>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_customer_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Food Cart" , root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Food Cart</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <% if customer_signed_in? %>
            <li class="nav-item">
              <%= button_to "Log out" , destroy_customer_session_path, method: :delete, class: "nav-link active"%>
            </li>
            <li class="nav-item">
              <%= link_to "Profile", edit_customer_registration_path, class: "nav-link active"%>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign in" , new_customer_session_path, class: "nav-link active"%>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up" , new_customer_registration_path, class: "nav-link active"%>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Food Cart" , root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Food Cart</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <% if customer_signed_in? %>
            <li class="nav-item">
              <%= button_to "Log out" , destroy_customer_session_path, method: :delete, class: "nav-link active"%>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign in" , new_customer_session_path, class: "nav-link active"%>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up" , new_customer_registration_path, class: "nav-link active"%>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>